### ISSUE TITLE
Remove bulk_pull_blocks 

### ISSUE THREAD

**Issue by wezrule** [nanocurrency/protocol#11]
`bulk_pull_blocks` was removed in https://github.com/nanocurrency/nano-node/pull/1615 in v18, can probably be removed from here now.

**Comment by zhyatt** [comment]
Node V18 is still [active](https://docs.nano.org/releases/node-releases/#active-releases) until V21 upgrades, so I vote we do this change once we do the epoch v2 distribution (most network upgraded to V21).

**Comment by zhyatt** [comment]
@SergiySW Is this a good time to remove `bulk_pull_blocks` here?
